apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mines01-pvc
  namespace: minecraft
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
