{
 "title": "OPNSense",
 "description": "OPNSense metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job Name",
    "query": {
     "query": "label_values(node_uname_info{job=\"opnsense\"},job)"
    }
   },
   { "name": "wan_interface_1", "label": "WAN Interface 1", "query": { "query": "label_values(device)" } },
   { "name": "wan_interface_2", "label": "WAN Interface 2", "query": { "query": "label_values(device)" } },
   { "name": "lan_interface_1", "label": "LAN Interface 1", "query": { "query": "label_values(device)" } },
   { "name": "lan_interface_2", "label": "LAN Interface 2", "query": { "query": "label_values(device)" } },
   {
    "name": "fs_type",
    "label": "Filesystem Type",
    "query": {
     "query": "label_values({fstype=\"zfs\"},fstype)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_cpu_temperature_celsius{job=\"$job\",cpu=\"0\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"$job\"} - node_boot_time_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"$job\",mode=\"idle\"}[1m])) * 100 / scalar(count(node_cpu_seconds_total{job=\"$job\",mode=\"user\"}))"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_free_bytes{job=\"$job\"} + node_memory_inactive_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Free Swap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_swap_size_bytes{job=\"$job\"} - node_memory_swap_used_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Load Average 1m",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"$job\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{job=\"$job\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{job=\"$job\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_exec_forks_total{job=\"$job\"}",
     "legendFormat": "Forks"
    },
    {
     "expr": "node_exec_system_calls_total{job=\"$job\"}",
     "legendFormat": "System Calls"
    },
    {
     "expr": "node_exec_traps_total{job=\"$job\"}",
     "legendFormat": "Traps"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " irate(node_exec_device_interrupts_total{job=\"$job\"}[5m])",
     "legendFormat": "interrupts"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_exec_context_switches_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAN 1 In/Out",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\",device=\"$wan_interface_1\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{job=\"$job\",device=\"$wan_interface_1\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "WAN 2 In/Out",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\",device=\"$wan_interface_2\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{job=\"$job\",device=\"$wan_interface_2\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "LAN 1 In/Out",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\",device=\"$lan_interface_1\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{job=\"$job\",device=\"$lan_interface_1\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "LAN 2 In/Out",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\",device=\"$lan_interface_2\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{job=\"$job\",device=\"$lan_interface_2\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "WAN 1 Receive Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{job=\"$job\",device=\"$wan_interface_1\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_multicast_total{job=\"$job\",device=\"$wan_interface_1\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_drop_total{job=\"$job\",device=\"$wan_interface_1\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_errs_total{job=\"$job\",device=\"$wan_interface_1\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  },
  {
   "title": "WAN 2 Receive Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{job=\"$job\",device=\"$wan_interface_2\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_multicast_total{job=\"$job\",device=\"$wan_interface_2\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_drop_total{job=\"$job\",device=\"$wan_interface_2\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_errs_total{job=\"$job\",device=\"$wan_interface_2\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  },
  {
   "title": "LAN 1 Receive Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{job=\"$job\",device=\"$lan_interface_1\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_multicast_total{job=\"$job\",device=\"$lan_interface_1\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_drop_total{job=\"$job\",device=\"$lan_interface_1\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_errs_total{job=\"$job\",device=\"$lan_interface_1\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  },
  {
   "title": "LAN 2 Receive Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{job=\"$job\",device=\"$lan_interface_2\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_multicast_total{job=\"$job\",device=\"$lan_interface_2\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_drop_total{job=\"$job\",device=\"$lan_interface_2\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_errs_total{job=\"$job\",device=\"$lan_interface_2\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  },
  {
   "title": "WAN 1 Transmit Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"$job\",device=\"$wan_interface_1\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_multicast_total{job=\"$job\",device=\"$wan_interface_1\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{job=\"$job\",device=\"$wan_interface_1\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{job=\"$job\",device=\"$wan_interface_1\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  },
  {
   "title": "WAN 2 Transmit Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"$job\",device=\"$wan_interface_2\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_multicast_total{job=\"$job\",device=\"$wan_interface_2\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{job=\"$job\",device=\"$wan_interface_2\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{job=\"$job\",device=\"$wan_interface_2\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  },
  {
   "title": "LAN 1 Transmit Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"$job\",device=\"$lan_interface_1\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_multicast_total{job=\"$job\",device=\"$lan_interface_1\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{job=\"$job\",device=\"$lan_interface_1\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{job=\"$job\",device=\"$lan_interface_1\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  },
  {
   "title": "LAN 2 Transmit Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"$job\",device=\"$lan_interface_2\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_multicast_total{job=\"$job\",device=\"$lan_interface_2\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{job=\"$job\",device=\"$lan_interface_2\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{job=\"$job\",device=\"$lan_interface_2\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_active_bytes{job=\"$job\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_buffer_bytes{job=\"$job\"}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "node_memory_cache_bytes{job=\"$job\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "node_memory_free_bytes{job=\"$job\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_inactive_bytes{job=\"$job\"}",
     "legendFormat": "Inactive"
    },
    {
     "expr": "node_memory_laundry_bytes{job=\"$job\"}",
     "legendFormat": "Laundry"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_swap_in_bytes_total{job=\"$job\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_swap_size_bytes{job=\"$job\"} - node_memory_swap_in_bytes_total{job=\"$job\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "LAN2 In/Out",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\",device=\"igc2\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{job=\"$job\",device=\"igc2\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"$job\"}[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{job=\"$job\",mode=\"user\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  }
 ]
}