{
 "title": "BMC overview",
 "tags": [
  "dell",
  "idrac",
  "lenovo",
  "redfish"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": "label_values(idrac_system_machine_info,job)"
   },
   {
    "name": "instance",
    "query": "label_values(idrac_system_machine_info{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Health",
   "type": "stat",
   "description": "Servers with health problems",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "idrac_system_health{instance=~\"$instance\", job=~\"$job\"} > 0",
     "legendFormat": "{{instance}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Health",
   "type": "status-history",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "idrac_system_health{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Temperature Inlet",
   "type": "timeseries",
   "description": "Top 10",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "topk(10, avg_over_time(idrac_sensors_temperature{instance=~\"$instance\",job=~\"$job\", name=~\"System Board Inlet Temp|Inlet.*|.*Ambient.*\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}: {{name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "avg (avg_over_time(idrac_sensors_temperature{instance=~\"$instance\",job=~\"$job\", name=~\"System Board Inlet Temp|Inlet.*|.*Ambient.*\"}[$__rate_interval]))",
     "legendFormat": "Mean: Inlet"
    }
   ]
  },
  {
   "title": "Temperature Outlet",
   "type": "timeseries",
   "description": "Top 10",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(idrac_sensors_temperature{instance=~\"$instance\",job=~\"$job\", name=~\"Out.+|.*Exhaust.*\"}[$__rate_interval]))",
     "legendFormat": "Mean: Outlet"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "topk(10, avg_over_time(idrac_sensors_temperature{instance=~\"$instance\",job=~\"$job\", name=~\"Out.+|.*Exhaust.*\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}: {{name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Temperature other",
   "type": "timeseries",
   "description": "Top 10",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "topk(10, avg_over_time(idrac_sensors_temperature{instance=~\"$instance\",job=~\"$job\", name!~\"CPU.+|.*Inlet.*|.*Ambient.*|Out.+|.*Exhaust.*\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}: {{name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "avg(avg_over_time(idrac_sensors_temperature{instance=~\"$instance\",job=~\"$job\", name!~\"CPU.+|.*Inlet.+|Out.+|.*Exhaust.*\"}[$__rate_interval]))",
     "legendFormat": "Mean: {{name}}"
    }
   ]
  },
  {
   "title": "Temperature CPU",
   "type": "timeseries",
   "description": "Top 10",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "topk(10, avg_over_time(idrac_sensors_temperature{instance=~\"$instance\",job=~\"$job\", name=~\"CPU.+\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}: {{name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "avg(avg_over_time(idrac_sensors_temperature{instance=~\"$instance\",job=~\"$job\", name=~\"CPU.+\"}[$__rate_interval]))",
     "legendFormat": "Mean: CPU temp"
    }
   ]
  },
  {
   "title": "Fans",
   "type": "timeseries",
   "description": "Fastest/Slowest",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "bottomk(10,avg_over_time(idrac_sensors_fan_speed{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}: {{name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "topk(10,avg_over_time(idrac_sensors_fan_speed{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}: {{name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Power",
   "type": "status-history",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "idrac_system_power_on{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(avg_over_time(idrac_power_control_avg_consumed_watts{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Total power",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Power Supplies (output)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "max_over_time(idrac_power_supply_output_watts{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: Output PSU-{{id}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Event log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "System Event Log (SEL)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "last_over_time(idrac_events_log_entry{job=~\"$job\", instance=~\"$instance\"}[$__interval] offset -$__interval) * 1000 < ${__to}\nand \nlast_over_time(idrac_events_log_entry{job=~\"$job\", instance=~\"$instance\"}[$__interval] offset -$__interval) * 1000 > ${__from}",
     "legendFormat": "{{ id }}: {{ message }}"
    }
   ]
  }
 ]
}