openebs:
  zfs-localpv:
    crds:
      zfsLocalPv:
        enabled: true
      csi:
        volumeSnapshots:
          enabled: true
    # --- ADD THIS BLOCK TO FIX KUBEVIRT OVERFLOW ---
    node:
      env:
        - name: ALLOWED_TOPOLOGY_KEYS
          value: "kubernetes.io/hostname"
    # -----------------------------------------------
  lvm-localpv:
    crds:
      lvmLocalPv:
        enabled: false
      csi:
        volumeSnapshots:
          enabled: false
  mayastor:
    csi:
      node:
        initContainers:
          enabled: false
  engines:
    local:
      lvm:
        enabled: false
      zfs:
        enabled: true
    replicated:
      mayastor:
        enabled: false

  loki:
    enabled: false        

  alloy:
    enabled: false
