openebs:
  # 1. Turn it OFF here to silence the first hidden engine template copy
  csi:
    volumeSnapshots:
      enabled: false

  zfs-localpv:
    crds:
      zfsLocalPv:
        enabled: true
      # 2. Turn it OFF here too (Highly Recommended for GitOps/ArgoCD)
      csi:
        volumeSnapshots:
          enabled: false

  # Keep your remaining configuration intact below
  lvm-localpv:
    enabled: false
    crds:
      lvmLocalPv:
        enabled: false
      csi:
        volumeSnapshots:
          enabled: false
  mayastor:
    enabled: false
    csi:
      node:
        initContainers:
          enabled: false
  engines:
    local:
      lvm:
        enabled: false
      zfs:
        enabled: true
    replicated:
      mayastor:
        enabled: false
  loki:
    enabled: false        
  alloy:
    enabled: false
