gpu-operator:
  cdi:
    enabled: true 

  nfd:
    enabled: true

  devicePlugin:
    enabled: true
    config:
      create: false
      name: time-slicing-config-all
      default: "time-slicing-config-all" 

  driver:
    enabled: false

  migManager:
    enabled: false
    config:
      create: false
      default: all-disabled
      name: default-mig-parted-config

  toolkit:
    enabled: true # Must be true for containers to actually use the GPU

  dcgm:
    enabled: true # Enable for health monitoring

  vgpuDeviceManager:
    enabled: false
    
  dcgmExporter:
    enabled: true
    serviceMonitor:
      enabled: true