kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: seerr-pvc
  namespace: torrent
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: openebs-zfspv-lz4
