---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: r2-backup-secret
spec:
  encryptedData:
    access-key-id: AgBL+zirhCSpY0P76LdHFAD02jGpOImTQVpzWBdLNmS3FT2w0n6Sxn+zSe0QQMxihcaiGp/G2ZUzfe8GGxFKfANCCxogJrQ5TT2F43OsZMIhsoySgyMWTYK2Hy/+RnwkS5PsFFrT01SzSiGQ0qnEtUjDFt60M/1hXJpkhmByQXkIZoFwHHcfJYAWPZYoVp8i+61UvAKGJe1v+AxXjR1zcnWlQCb1fdR95E3qgsH/k2ZWmHGf/EuMJg0LaqepqXPhXZejZmMMCH8v06JnuYEt4qPn1lowHtIbrRmSOSePruZ+SGcIXRJ5G7KS4DZIYV0iQUFpEjje6wIlHVZBhfcHjQl8WB5/oDHRv7TfYOKxsDAlLpz+xF250UfqS8Gau2qGlWTodxQndw3TdddmsOfo6bt8HDP03XVr+1+UkKwekd186DRT6/fUtFU7qCLF4G1uOE6naRwDbddNyRMY4P/Fv8/NzigxB+NiHfvqYM3mTIlCjxOdi2+k8E81izllQZc7G4ns+q6hUi2z9hdjGkwg0RNg6SAsTVbAJdH/NhEUK08rmYEZlYpienQErkKHX1kkHonFE1DNyLq2O4kdXasUhft/OMN7Aggu852agcEBn3LacyMPmb/r/YPLimesu+EqcX9qj8nsXKHGqadulHx6LPB3tMe9X4NNfs/o+ebLwF86Wu5cNBf8seN+/x8X4tY6jYn37sXWcxgX1F/wrs2ZWCneZRZ7IBegwfEXliDxRSEP3Q==
    secret-access-key: AgCc71AxwfJKdbGYX6sKmJF5CEUbAr8XfBAcd0kn9qqex3MBvOO2NzkVBYUlj8eQrJ2Z2Ho8SNSBVlVM9P1sCBAdv75sa25cTOKf0kY0mVVelzx2WGtcHHubm6d+308Z2mXpLArQgMxSqDzoqZo+6lB4SLcrw4OV6/Ii+g1xfFnflO4vxBS80eCRciA/EeccxNZsT9/fFo1BT0znIuK4DTjXTG3+KM9pov7QBA9OfqX9VW76Vp4cnltzElUCnw2cqigXGITTWXQiCtH9DgFvZSZQEdvMFDWsf25gvoKMsoBu5lmvLT6KrrpajGTofNZCaOnFiRVFpOvWdjOtrMTda+a6Vfg9Hv70pLqTfrESL0MFf4RCuoVXipz10ia39+uOWmv8iV6/b5kL+JtBoZHFsb75DVR8LR6vkVZvdmqsU3VZQTiYAfH9ogkpyqYHqAcwWU87/1DNY0xkQSM68FV2pv5vK9725i0MlMslZqkaGfRDfn3EOyMuj3HM4tKfwgBiDmaqkaHc0iuAVuD1VhEftNFrL+nQB46rqp8DzMXb0RE8Bdo7DG2x25BBZediLch/1M0UtpUSJYCBCl5T4k7cFtRLjUqVWgkWvjNT61jkqgO/JOxvId/jLFhtLeaaMfKr4Mts0B9Dq0SJq3Aeq/KrkRsy7IEavjNCTs/u3gtQl9hW54dompbmI9IhBOrrxsAcYf8ltl2bX0+xkoB8V41+g2hX/FH9kWl2UcniujYvPK95C1cMiLG/GLaxfPbYCoigmVDUqsr0SJTspw/RNYF+oq7n
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: r2-backup-secret
    type: Opaque
