---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: r2-backup-secret
  namespace: databases
spec:
  encryptedData:
    access-key-id: AgBHnstQBDTVfUD0BvEAznlK4ediIllu1VA9aOpLt/iaCOoEj5AydrbsTWEkqA1g0dj7J2G63YjeRuBmHldiVwBaBU4KxhTFv583DLJ+xQ5jbLNPPYSG6HDPpLnoiofvlfmg6vo2xyn5w0u4Mnpd2sMNtqL+mZOdELhvcetoi4kV+tTNW7Bfv5ZlihXaUQ8GyMT+4WR6Ex0tvTq0tgwzSH1AssZAr1IsRyxXosuJKcadRhLCPgt9vTcZE4gV4F8Suzvv5rcDi7IdTjMP9W6mytWH4B+BRv+3u1aiSuFcBcYgvHN2mpCRqHf/iG5V9XD7OU7aHnIVz7el5KiW9u+Np/DZZZLcXIb5ptY5cITTJd+t5yarCa6RuTKeyfnhI5i7eoK5z3qLb2JBtZ8KCs0Fn0DvMvcIED3Wn3KdW5YYomFVAA2z1oyGhvKh96ytPLNSoMPKN3exP88EUHGiflk734bqHh8s05xBBy4ObbEoQoNAqL6zfednBDlbsDKjMj/KQOan054DP2/kQuUvjFFYXJF295W6WAXZzS+Cf133Hz4vTvjoYhA/P0SKuWof1SvP/uprDtziaDZ+RLJTGBdEEuOQ4cH6fveAxDsRKO5IZeb04zzrdxvgsLMeN3WtV8lcIssmMMeVldkie+muTU0WdCv+GZemfjjYjLC+/ej1cSFUB17dkvzTkgBYKZt0CIJRFxVg276SQhkro4PPWD3OyupIIPMMnkwOAIiwEA/ZJg9mWw==
    secret-access-key: AgA/BvZBAtMXT/8oFtbu7OfgEE6N4LhH265hyiXciy1RrE5SkDK8pqwVnVPHpEsueyi9/YujGMg+Ucq5z8XKnL45Z9BmS6LaJceRO8zqYzgGx82O4u1+u8IP/XpfDnm7SsB8JFpKgHToy1Idh2ldFPgrgwLQE5vf7bbOI1t9rJB5mSjnC4SXhQsJn8lKfqTYeAKQMlYWEJKWW5UEYbKg5PWBCuLzB5w85IYcPGs4oMpJ1Fp6u1PknsBf5L1WUAOZwoKp+Q3xlCSUZe74Yf7yligZmqup0sZEkMZUnAG9jtC/pufdy8iiLp6abpDwK7PKLuN+kHEVOzelrnLIvKF3j5XQIZ8aeBEmCs/Rpe3dXqIMf2qoStBfV7+qS/iL+yOjZvq+03e00ZCGWfxsuOmUWrZtfW4weXLqUiXP8PB3qfcOKdVUFn936KI5vBPVv2CbUtWG4fUnJMJRQs/E3kfZu3RhCfKr4xRNMvqotH1IKwVbBTST/KeFxkO3Tyjf3YQZvbrFiD8Uqcwip2jXd8QNZzrQNZw6XB4gah8L0pyaxMKneURtWGFRm1E2DaobMsT4WuRdCTwtdIqMKXOqdZGV2w66JxzmbRy5Ocg4/V5ogQBbQ2B6h824GrOaNQ/cVe0/5xRLmFJOneIph8FTMsHBZ+x6oR3bKmROxNtH7flbkr8QMEyPyDSr+djHvYw+1h6i8JDOvcuExfGV9djJqzLgg8P+CuTJqbAWKjjr3cbMlhu8/zzktcm1T3L5pwsMjtMR1Qo5kvLCFAAtlRxxuPS81Tgl
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: r2-backup-secret
      namespace: databases
    type: Opaque
