---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: r2-backup-secret
  namespace: databases
spec:
  encryptedData:
    access-key-id: AgBh0JJleqERo06I+Juu0Mk0/FPzDGdTmzE1grJW/citp00YsFnBpjqbDhKX2DoGzxM0EuDwv9V6kHkP/B8KVWUzZfCIJTw5+U27GWlCi+0+Hg9ow8mJ+q+A4a7Scy+OoW8rB/ZvBqkms17ji7nkp315l4G/5mXNhMZTbLFq0XSnx2iNXQRxfxDsIh6JAd7XlNBfQmcOUIrueaUVpGuSdhFIP/cyWJs+lAc3cwSm3FAJTLZXrF03YmHv3zCKmLauwarDVcmKYuRzCRl7Ns9YpoB8rsmCXP1DVY86Nj/VnI8ZXaIeUdnPPka09YHROC9pfiZscifiTCRb1MyyF1Zvl/1v6pL+ELQotGwMCDQAZ+HSSsIxmwR/LhRxXJwrkvv0BPZAb1/gOeQUQF+OiZwKkeGmMwpKpjzBQbNiUgWiQx1H5yB4eo2O3DjQVb4BCE7mIvwlQDEEMIo2OYK3iyH44XzPi9RLNCBbLHOMCv3q06PjKlWLpZYSZR493xKp9L84zBIR4XKv8Izor9umVpM9OMeY0CceezWlsuHE5XWYiX7KPf/kMe2+p5WFND6vrogv8i7u6uY1hIVq7Ri5FhbTzKf51mOqE+wn+b2ap+s82UnjpWo7TWH8WsKDpeBLly+2GXSX6VgWXPZGZg02dBOs7KSmiaoM2nxgI5uyGfTiTEvtunzPWkicA+YnjH0zcBE1ElEEn/TWcOu9xXFRNg8b3yr+ROmgwAscvoDRqPddgY5tjg==
    secret-access-key: AgBWGpnxhAw/s2z1vmWYm7eVhz4+RQnS4tqrxKF1ctDBDRKdBj5H+IjMrd7Kt/mfG3NgqvD7Ch0xPMygxWJXU2QvCAZ7G/N+UmQ+3F9+/FVigzzyg0xsAvrPmflbByh8qSDbMNxVy2VAh/b0lrAB/7H5oI72MKYrKCMiREnqvjDWfFCqvElFDrkxQLjVXDTTk4hdosGuDcn0QxcX4urGMeZqlhL6t1ih+XC2LkrrjDJNLV0mx2Vux1TlHLOmDmWBUIIa05RbFGAAldtqhmZFQqkBev9OkYwH9pQW21aKXwAgvwROHcxgPXl01qjjILKT194gEPsNaCzPW67S7cM/WDldEB3g3a/SFUvA25k4hjpRIfLvK78VxYw8ukxRjGOTZcJNHb8Q4mo/fyTuJetMSHuRz/2sc2PlGP282CrIpOGgXDuJFBMBZuFluIsLGnRe7Sf1v5AaHfecisJRkFN1WOfIlYJwSU2hQYtnzakQLkhlw6LDvQ0oNWJ/Eo4tRi/BDlNtolTWf0EVBiPi0Kg3oEdx9SKPOi0+jOnMHk4OyucZV1jElAqy08u0W2WLGq9/0OIJxljM1uU8lI5CQvB2mGWRaBZeNSSeNdm/TzVrx72tWNkIHhRPvyc7o3vNgsEB4778pDZG1GW6Rnuz3ZRATo2vyB4XiJeNPO3Jk0ilF/o8+3jDFLSoDSIX89VoKwDYLvZC9fyIq+MUTt717Y15UZPruUXz4evxr//yy8GN9ahX1TKKjU2uj631hKF3eaUtaahmp0oEU4GjJz61Oi71bSGg
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: r2-backup-secret
      namespace: databases
