apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rspamd-pvc
  namespace: mail
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: openebs-zfspv-lz4
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
