apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: smallstep-smallstep-daily-local
  namespace: velero
spec:
  schedule: CRON_TZ=America/New_York 0 5 * * *
  skipImmediately: false
  template:
    includedNamespaces:
      - smallstep
    includedResources:
      - '*'
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: smallstep
    ttl: 168h0m0s
    snapshotVolumes: true
    snapshotMoveData: false
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: smallstep-smallstep-weekly-offsite-cfr2
  namespace: velero
spec:
  schedule: CRON_TZ=America/New_York 0 5 * * 3
  skipImmediately: false
  template:
    includedNamespaces:
      - smallstep
    includedResources:
      - '*'
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: smallstep
    ttl: 720h0m0s
    snapshotVolumes: true
    snapshotMoveData: true
