apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata: 
  name: operator-bundle
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
    - merge:
        mergeKeys:
          - appName
        generators:
          - git:
              repoURL: 'https://github.com/nforceroh/k8s-home.git'
              revision: main
              directories:
                - path: virt01/automated/operators/*
              exclude:
                - path: virt01/automated/operators
              values:
                appName: "{{`{{path.basename}}`}}"                
          - list:
              elements:
                - appName: cnpg-operator
                  targetNamespace: cnpg-system
                - appName: gpu-operator
                  targetNamespace: gpu-operator
                - appName: cert-manager
                  targetNamespace: cert-manager
                - appName: multus-cni
                  targetNamespace: multus-cni
                - appName: traefik
                  targetNamespace: traefik
                - appName: metallb
                  targetNamespace: metallb-system
  template:
    metadata:
      name: "{{`{{appName}}`}}"
    spec:
      project: argocd-virt01
      source:
        repoURL: 'https://github.com/nforceroh/k8s-home.git'
        targetRevision: main
        path: "{{`{{path}}`}}"
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: "{{`{{targetNamespace}}`}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
