apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tools

labels:
  - pairs:
      app: poweradmin

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - serviceaccount.yaml

secretGenerator:
- name: poweradmin-env
  envs:
  - env/env.txt

generatorOptions:
  disableNameSuffixHash: true