apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: mail-postfix-daily-local
  namespace: velero
  annotations:
    argocd.argoproj.io/sync-options: ForceNamespace=velero
spec:
  schedule: CRON_TZ=America/New_York 15 3 * * *
  skipImmediately: false
  template:
    includedNamespaces:
      - mail
    includedResources:
      - '*'
    labelSelector:
      matchLabels:
        app: postfix
    ttl: 168h0m0s
    snapshotVolumes: true
    snapshotMoveData: false
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: mail-postfix-weekly-offsite-cfr2
  namespace: velero
  annotations:
    argocd.argoproj.io/sync-options: ForceNamespace=velero
spec:
  schedule: CRON_TZ=America/New_York 15 3 * * 3
  skipImmediately: false
  template:
    includedNamespaces:
      - mail
    includedResources:
      - '*'
    labelSelector:
      matchLabels:
        app: postfix
    ttl: 720h0m0s
    snapshotVolumes: true
    snapshotMoveData: true
