apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: torrent-seerr-daily-local
  namespace: velero
  annotations:
    argocd.argoproj.io/sync-options: ForceNamespace=velero
spec:
  schedule: CRON_TZ=America/New_York 30 6 * * *
  skipImmediately: false
  template:
    includedNamespaces:
      - torrent
    includedResources:
      - '*'
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: seerr
    ttl: 168h0m0s
    snapshotVolumes: true
    snapshotMoveData: false
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: torrent-seerr-weekly-offsite-cfr2
  namespace: velero
  annotations:
    argocd.argoproj.io/sync-options: ForceNamespace=velero
spec:
  schedule: CRON_TZ=America/New_York 30 4 * * 3
  skipImmediately: false
  template:
    includedNamespaces:
      - torrent
    includedResources:
      - '*'
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: seerr
    ttl: 720h0m0s
    snapshotVolumes: true
    snapshotMoveData: true
