# https://github.com/bitnami/charts/blob/main/bitnami/phpmyadmin/values.yaml

pgadmin4:
  image:
    tag: "9"

  auth:
    email: "sylvain@nf.lab"
    existingSecret: pgadmin-auth
    passwordKey: password

  persistence:
    enabled: true
    size: "1Gi"