apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tools

labels:
  - pairs:
      app: strix

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml

generatorOptions:
  disableNameSuffixHash: true