apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strix-pvc
  namespace: camera # Keeping with your existing namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
