gpu-operator:
  cdi:
    enabled: false
    default: false

  nfd:
    enabled: true

  devicePlugin:
    enabled: true
    config:
      create: false
      name: time-slicing-config-all
      default: "time-slicing-config-all" 

  driver:
    enabled: true
    usePrecompiled: true
    version: "580.126.16" 
    nvidiaDriverCRD:
      enabled: false
    kernelModuleConfig:
      name: "nvidia-params"

  migManager:
    enabled: false
    config:
      create: false
      default: all-disabled
      name: default-mig-parted-config

  toolkit:
    enabled: true # Must be true for containers to actually use the GPU

  dcgm:
    enabled: true # Enable for health monitoring

  dcgmExporter:
    enabled: true
    serviceMonitor:
      enabled: true