apiVersion: v2
name: multus
description: Wrapper chart for Multus CNI
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: multus
    version: "*"
    repository: https://k8snetworkplumbingwg.github.io/helm-charts