# Kernel/NFS Tuning
fs.inotify.max_queued_events=1000000
fs.inotify.max_user_instances=1000000
fs.inotify.max_user_watches=2000000
net.core.somaxconn=8192
net.ipv4.ip_local_port_range=1024 65535

# Memory & Swap
vm.swappiness = 10
vm.overcommit_memory = 1

# I/O Smoothing (Replaces dirty_ratio)
# Start background writes at 256MB
vm.dirty_background_bytes = 268435456
# # Force synchronous writes / throttle at 1GB
vm.dirty_bytes = 1073741824

# Fix NFS Performance Bottlenecks
sunrpc.tcp_slot_table_entries = 128
sunrpc.udp_slot_table_entries = 128

# Increase Network Buffers for high-speed NAS traffic
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216

# Speed up Samba/SMB connection handling
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_tw_reuse = 1