apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: iot-mosquitto-daily-local
  namespace: velero
spec:
  schedule: CRON_TZ=America/New_York 10 2 * * *
  skipImmediately: false
  template:
    includedNamespaces:
      - iot
    includedResources:
      - '*'
    labelSelector:
      matchLabels:
        app: mosquitto
    ttl: 168h0m0s
    snapshotVolumes: true
    snapshotMoveData: false
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: iot-mosquitto-weekly-offsite-cfr2
  namespace: velero
spec:
  schedule: CRON_TZ=America/New_York 10 2 * * 3
  skipImmediately: false
  template:
    includedNamespaces:
      - iot
    includedResources:
      - '*'
    labelSelector:
      matchLabels:
        app: mosquitto
    ttl: 720h0m0s
    snapshotVolumes: true
    snapshotMoveData: true
