{
 "title": "UPS Dashboard",
 "description": "https://technicalramblings.com/blog/monitoring-your-ups-stats-and-cost-with-influxdb-and-grafana-on-unraid-v2-0/",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "kwhprice",
    "label": "kWh Price",
    "query": "0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09,0.1,0.11,0.12,0.13,0.14,0.15,0.16,0.17,0.18,0.19,0.2,0.3,0.4,0.5,0.6,0.65,0.7,0.8,0.9,1"
   },
   {
    "name": "dynamicbucket",
    "query": "    //Bucketfilter to filter only buckets beginning with name upsdata..\r\n    bucketfilter = /upsdata.*/\r\n\r\n    buckets()\r\n    |> filter(fn: (r) => r.name =~ bucketfilter)\r\n    //convert retentionperiod from nanosecond to days\r\n    |> map(fn: (r) => ({r with retentionPeriodinDays: r.retentionPeriod / 86400000000000})   )\r\n    //replace retentionpolicy infinity with a high number in NS\r\n    |> map(fn: (r) => ({r with retentionPeriod: if r.retentionPeriod == 0 then 999999999999999999\r\n        else r.retentionPeriod})\r\n    )\r\n    //calculate the duration from \"to\" and \"from\" timespan and convert it to nanosecond\r\n    |> map(fn: (r) => ({r with \r\n        DashboardDurationinNS: (${__to} - ${__from}) * 1000000})\r\n    )\r\n    |> filter(fn: (r) => \r\n        r.DashboardDurationinNS <= r.retentionPeriod and\r\n        r.retentionPeriod >= uint(v: now()) - uint(v: ${__from} * 1000000)\r\n    )\r\n    |> sort(columns: [\"retentionPeriod\"], desc: false)\r\n    |> limit(n: 1)\r\n    |> keep(columns: [\"name\"]) //remove all fields except for \"name\""
   }
  ]
 },
 "panels": [
  {
   "title": "UPS Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Alpha UPS Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_load",
     "query": "from(bucket: \"${dynamicbucket}\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.load\")\r\n  |> aggregateWindow(every: 1m , fn: mean, createEmpty: true)\r\n  |> yield()  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups", "operator": "=", "value": "E5130_A" }
     ]
    },
    {
     "alias": "Alpha Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_power",
     "query": "from(bucket: \"${dynamicbucket}\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: true)\r\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: true)\r\n  |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups", "operator": "=", "value": "E5130_A" }
     ]
    },
    {
     "query": "from(bucket: \"${dynamicbucket}\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: true)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"ups\", \"_measurement\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: true)\r\n  |> drop(columns: [\"_field\"])\r\n  |> yield(name: \"TotalPowerUsage\")"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"upsdata/autogen\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"battery.charge\")\r\n  |> filter(fn: (r) => r[\"ups\"] == \"E5130_A\" or r[\"ups\"] == \"E5130_B\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"${dynamicbucket}\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"input.voltage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")  "
    }
   ]
  },
  {
   "title": "Current UPS Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "E5130_A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_load",
     "query": "from(bucket: \"upsdata/autogen\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.load\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups", "operator": "=", "value": "E5130_A" }
     ]
    }
   ]
  },
  {
   "title": "Average UPS Power Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "E5130_A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_power",
     "query": "from(bucket: \"upsdata/autogen\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups", "operator": "=", "value": "E5130_A" }
     ]
    }
   ]
  },
  {
   "title": "This Week Consumption/Costs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "PowerUsage = from(bucket: \"upsdata/week\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> filter(fn: (r) => r[\"ups\"] == \"E5130_A\" or r[\"ups\"] == \"E5130_B\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: true)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"ups\", \"_measurement\"])\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0}))\r\n  |> yield(name: \"PowerUsage\")\r\n"
    },
    {
     "query": "PowerCost = from(bucket: \"upsdata/week\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> filter(fn: (r) => r[\"ups\"] == \"E5130_A\" or r[\"ups\"] == \"E5130_B\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: true)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"ups\", \"_measurement\"])\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0*${kwhprice}}))\r\n  |> yield(name: \"PowerCost\")"
    }
   ]
  },
  {
   "title": "UPS Status E5130_A",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "E5130_B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "ups_status",
     "query": "from(bucket: \"upsdata/autogen\")\r\n  |> range(start: -10m) \r\n  |> filter(fn: (r) => r[\"ups\"] == \"E5130_A\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.status\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ups", "operator": "=", "value": "E5130_B" }
     ]
    }
   ]
  },
  {
   "title": "UPS Status E5130_B",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "E5130_B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "ups_status",
     "query": "from(bucket: \"upsdata/autogen\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r[\"ups\"] == \"E5130_B\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.status\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ups", "operator": "=", "value": "E5130_B" }
     ]
    }
   ]
  },
  {
   "title": "UPS Runtime",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "E5130_A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "battery_runtime",
     "query": "from(bucket: \"upsdata/autogen\")\r\n  |> range(start: -10m) \r\n  |> filter(fn: (r) => r[\"_field\"] == \"battery.runtime\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ups", "operator": "=", "value": "E5130_A" }
     ]
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "E5130_A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "charge_percent",
     "query": "from(bucket: \"upsdata/autogen\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"battery.charge\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups", "operator": "=", "value": "E5130_A" }
     ]
    }
   ]
  },
  {
   "title": "Estimated Daily KW/h",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"upsdata/autogen\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"ups\", \"_measurement\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: true)\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0 * 24.0}))  "
    }
   ]
  },
  {
   "title": "Estimated Daily $",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"upsdata/autogen\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"ups\", \"_measurement\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: true)\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0 * 24.0 * ${kwhprice}}))\r\n"
    }
   ]
  },
  {
   "title": "Last 30 Days Consumption/Costs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "PowerUsage = from(bucket: \"upsdata/month\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> filter(fn: (r) => r[\"ups\"] == \"E5130_A\" or r[\"ups\"] == \"E5130_B\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: true)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"ups\", \"_measurement\"])\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0}))\r\n  |> yield(name: \"PowerUsage\")\r\n"
    },
    {
     "query": "PowerCost = from(bucket: \"upsdata/month\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> filter(fn: (r) => r[\"ups\"] == \"E5130_A\" or r[\"ups\"] == \"E5130_B\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: true)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"ups\", \"_measurement\"])\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0*${kwhprice}}))\r\n  |> yield(name: \"PowerCost\")"
    }
   ]
  },
  {
   "title": "Instant Usage Estimate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"upsdata/autogen\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"ups\", \"_measurement\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: true)\r\n  |> last()\r\n  |> map(fn: (r) => ({r with _value: r._value/1000.0 }))  "
    }
   ]
  },
  {
   "title": "Instant Cost Estimate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"upsdata/autogen\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"ups\", \"_measurement\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: true)\r\n  |> last()\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0 * ${kwhprice}}))\r\n"
    }
   ]
  },
  {
   "title": "Last 24hrs Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"upsdata/day\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"ups\", \"_measurement\"])\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n  |> map(fn: (r) => ({r with _value: r._value * 24.0 / 1000.0}))"
    }
   ]
  },
  {
   "title": "Last 24hrs Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"upsdata/day\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"ups\", \"_measurement\"])\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n  |> map(fn: (r) => ({r with _value: r._value * 24.0 / 1000.0*${kwhprice}}))\r\n"
    }
   ]
  },
  {
   "title": "Last 7 Days Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"upsdata/week\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"ups\", \"_measurement\"])\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n  |> map(fn: (r) => ({r with _value: r._value * 24.0 / 1000.0}))"
    }
   ]
  },
  {
   "title": "Last 7 Days Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"upsdata/week\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"ups\", \"_measurement\"])\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n  |> map(fn: (r) => ({r with _value: r._value * 24.0 / 1000.0*${kwhprice}}))\r\n"
    }
   ]
  },
  {
   "title": "Last 365 Days Consumption/Costs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "PowerUsage = from(bucket: \"upsdata/year\")\r\n  |> range(start: -365d)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> filter(fn: (r) => r[\"ups\"] == \"E5130_A\" or r[\"ups\"] == \"E5130_B\")\r\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: true)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"ups\", \"_measurement\"])\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n  |> map(fn: (r) => ({r with _value: r._value *24.0 /1000.0}))\r\n  |> yield(name: \"PowerUsage\")"
    },
    {
     "query": "PowerUsage = from(bucket: \"upsdata/year\")\r\n  |> range(start: -365d)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> filter(fn: (r) => r[\"ups\"] == \"E5130_A\" or r[\"ups\"] == \"E5130_B\")\r\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: true)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"ups\", \"_measurement\"])\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n  |> map(fn: (r) => ({r with _value: r._value *24.0 /1000.0* ${kwhprice}}))\r\n  |> yield(name: \"PowerUsage\")"
    }
   ]
  },
  {
   "title": "Last 30 Days Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"upsdata/month\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: true)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"ups\", \"_measurement\"])\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n  |> map(fn: (r) => ({r with _value: r._value *24.0 / 1000.0}))"
    }
   ]
  },
  {
   "title": "Last 30 Days Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"upsdata/month\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: true)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"ups\", \"_measurement\"])\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n  |> map(fn: (r) => ({r with _value: r._value *24.0 / 1000.0 *${kwhprice}}))\r\n"
    }
   ]
  },
  {
   "title": "Last 365 Days Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"upsdata/year\")\r\n  |> range(start: -365d)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: true)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"ups\", \"_measurement\"])\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n  |> aggregateWindow(every: 365d, fn: sum, createEmpty: true)\r\n  |> map(fn: (r) => ({r with _value: r._value *24.0 / 1000.0}))"
    }
   ]
  },
  {
   "title": "Last 365 Days Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"upsdata/year\")\r\n  |> range(start: -365d)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups.power\")\r\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: true)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"ups\", \"_measurement\"])\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: true)\r\n  |> aggregateWindow(every: 365d, fn: sum, createEmpty: true)\r\n  |> map(fn: (r) => ({r with _value: r._value *24.0 / 1000.0*${kwhprice}}))\r\n"
    }
   ]
  }
 ]
}