apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: databases-postgresql-daily-local
  namespace: velero
spec:
  schedule: CRON_TZ=America/New_York 20 1 * * *
  skipImmediately: false
  template:
    includedNamespaces:
      - databases
    includedResources:
      - '*'
    labelSelector:
      matchLabels:
        app: postgresql
    ttl: 168h0m0s
    snapshotVolumes: true
    snapshotMoveData: false
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: databases-postgresql-weekly-offsite-cfr2
  namespace: velero
spec:
  schedule: CRON_TZ=America/New_York 20 1 * * 3
  skipImmediately: false
  template:
    includedNamespaces:
      - databases
    includedResources:
      - '*'
    labelSelector:
      matchLabels:
        app: postgresql
    ttl: 720h0m0s
    snapshotVolumes: true
    snapshotMoveData: true
