---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: pg-db-superuser
  namespace: databases
spec:
  encryptedData:
    password: AgARz+uJQ86e8O8wW7VUL12+g2fdSyhEoO1DbLcTYXsMf+fQnD9622L/R16NXlQaZrTnbjf4uDIyLaHhKWfTYBjC/Hg85mW8Q6JzgM1MfIqRdQMbpcJnlN9taaY38xK7JcbNN27DmyNHwJ+zefghoz6V3gb4L31DTqM8nBK0d8UQjrIz64Z0niD3+m1FFsJbbRFZKrlQ+qHMzj4sDXsJRoxbs8FBHG7CFpqkvCPQfCtVa/riZc4AzR7rbfpUO/xoAn4WbEuGiFfHgwYtkrZzmqKoP/5XK1bwx16dFLBRzQgactUbJwhwTk69r/VrEFJAPV42GmmAFjbleqNQ6OPgFIQPfvvbdc94G+72tjdM3Q7FSaFOH0JwRnTB0wxn4853gJy0OHzWXkhZfENsijPpmD/Whlyz0pR8u/goyr8nbGIFBduE3LjvOePycB9zdMlJKVOcXoANMlF39wb4A0UUhMnyXw4GSBqJDmB/ZArivb26MV9KAq+wFAJzwrcES4DkrVDuGaN+fjyNGnaUYp7a4CP1gP0daGBFweKGvRFcAUODBwUv4gvZbvIvhOEiEkmLL7ox4fqqjd2gJFpD9cyD6UuQa7UMXiK5m2zoqNus0F/eoLgGCwda/lkF2OjUKuLU2wo7iNXEmTANNrOcYEq9iBpgOj9+E0JV4wkdiyi9W0ILH21d8IkXDremlDOagOm830cRZZXik+YTlWLH8Q==
    username: AgA0iM0f5e9MHs7lCPy4waJjpPqrhBRuO44hS0tpZBOeAjcXK/IHWAezObBZpDhmH2HC0Kk8qvnpMwaq4FivT6NTSq/jW8TVSIB38ZVq/ZwvW161TPlGKed07WJ8EzfZCf2EiOy321M3n7cf2pENYUmgg4RukAzRDIyGj2B1zr7/Qzn5pVeOwJmLkmlo0KtyXrPBgTA7WM8y9XbsDMP5fWuIPNn2mtpU1s8CzyHFRE5LAJokdHI3/u7hHi30Qq+N8NWDO/upMHX0zE8cHBuOotzjPKYUsFfhdoX5KaZ7w8DVA9itFSf9QZbpX4+7yF+69yiBlMpoWyFNPwAX91WBy+B0+XDKVZrobmZT9f76IYfzDAT22QhfxLeyEjDbU7wJu+5AE4W8i/JyG02P5OEkRrYcLCjHC9u9WVebe5pnTHu2qtPlkz+JXK4OZrOE8+D2aFekLQcQX+CIsExI3a84IUCncxQ8/LwrKUMyDsg5Ac6OpnXx0cgKvTvkj51DSElpbLhSNfTIL92HdcXUg7Y4CrdRidOaUOhoeffj4mT0oAsgikzJ3VXtPHlFGFz3cav2nvunaHB3V53iVT1moRwK2mrxzX0WjA0UqeB+JIYg78G6AG2xZ+d3OiO0BtPxFt0D1CSymYn3VWR70hZDB7fSM8l32RZrY4TwEB2+K+eRXUXuntXd49NPPBW96V6pE6dR3WidMkD4vg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: pg-db-superuser
      namespace: databases
