apiVersion: v2
name: mariadb-operator
version: 1.0.2
dependencies:
- name: mariadb-operator
  repository: https://helm.mariadb.com/mariadb-operator
  version: 26.10.1
sources:
  - https://helm.mariadb.com/mariadb-operator
