name: mariadb
apiVersion: v2
version: 1.0.17
dependencies:
- name: mariadb
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 27.0.7
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/mariadb
