---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: audiomuse-ai-config
  namespace: torrent
spec:
  encryptedData:
    POSTGRES_DB: AgDEzPkVWKHCzednl3CJUPYG9u+14lg2L5yYmIjrc81BaSvVT01peJNPCvRuvPh2JQIInSQ/sFQIYbGdJeYyhn4W3GaW+u9vKZtHn0OHJpilgG5NkIzDdGR0otk02/I+8MnlhPJPodva5PZXDYsAlnkeHjbruoFj9z/s+Clw8DPYLUbayD2rpbkXKSPMdj3OGFPaxXdD1sxQywf/qhPdv5DmVWu4/8LIx87Dvlgbgs6tCOBA6wJ3VHis7pGqktN+sluM+Ux2qJxr63HKHnrIBDZILJr5jPcSmyWvRYAmuXG7FiRAe+4rUyF8/qmW/T9QSLcCqWiMVnk5GYHj7u1DOoGuRjtpur9jby3ZU4HYBlipSAInA07AQnC7qBTOq4EgtAqpucqC/2TXipYYxnTbgrF3MEAqwMaAjhs8+BUvW19gaW2dwgqisjAq3Y1MdtqZLQ5NfH3vlTmgMYjLC7PYl/UY3e0NJ1zZxmfWVZxxAwDz7j7cCTe6MoTd5GCaRhq/V/wQ8zKR4bPowOWLiN6+hB9aJu/5rAyv3NGbE2s2wwywk9aQ1U6gfCTIqq5NmxrrUBViGQmBA7k+mGzSd/kfwUL/fEfOuY1kZdBf7wDZ4DEoiFu3CVjJR2+PKRi3qVcPt9AMLqbnyk5eLV56UpbUKiuAHJhSv0lArvx95hb0x997DmOVgCY9KPorUHIUTlbz7YREOtw=
    POSTGRES_PASSWORD: AgDEdj/Eh6+epNYN4XV4Vuki8UkW1Il32r9mJl3r3Wu6Wf1Gztcd4T6k6m85csoSxsKlB7GkwXGNhFjvx1WCVzlCN+ssVH8lvaq+8eoYho1UZIrW5499QZbBvxHNMZ6dNon+PTjP3qpcIdyS+u8UmUO6xPUnqfU8OmU06RMcxYTC1+nm0r2RzOgD+DG4f0l4+dwx7REq64pbQy4wz9RG9SEUufjreKvIcJ6pxf96QG/j+qovaRJKy74FPdHCU3QPPLzFsyzC8jRLg2ShVPJd6OWwtDiPhm9ohKMFzlCAoqZBZA/FNgcxgLDTdi22ZtwJfW6kcXQ+8i9IA8HzrZtpXbmevMX4HJDiGFanrUYSuF73GrQaQ6MnpaSb2UnmM5gMoJAJBz4av8CUmh1dQnTIgtRrOSl6qMdXcS03PT1faAVze/Z/eoEMidqxSk+zGJFVnRsTj/unOEIhVEmviw0MK9Gt71pfMnBtUdeuadzk9/EiAZtiCta3OdrwKvs5NEBW77FDz6lMN32e3W4zhZAg5HVLd1r+cpW3J2vX8V9siHCr9TaNuz+ZqCyNoB11hnsdKz2pSbdNpYEDF0kfX+MF6zF1UgLbcJWO/mxuFx96jNVW7zHaPb/JWcFfU2x5c97xbwrGp8Q/4vH54kVi93ndVUIN6YE1CsnLtfM1zNT+4bRKVhJKeIa2jDE0SfhWo2fGEoHPGfboPmhTP0dBMQ==
    POSTGRES_USER: AgAcVoJWUTwb6iDaQ7DKeiFtYphVgkJb1sb3c0KVGJ2LE2wHQPW0VYkWKFs7TCNCiYpkRRwuEbqc/iC5/QsHFe8p/3UBH3W7crsTzs9wELd/3v2PS94+tusYEqN8W9MspRrfuVogg36HXkcnINnc6kpWOV8Q2RSSP3jzzVMq59ZRdGUq2xYwPPBgrnsg2DZPmuEATm92Jg8pYOtOvev3uJDVp8ptn1qw0mC3oYRjFMf9+7CKYboE4IbuccL50HNZ05tL72WzBWGsWmT1p27+s0fZfuUCh+f6hUicYYsdtt9eI20d36IBFGKQTy4gY4+ZIQ6M62rTXzKZIGA58dPxN/nzBmcFcl8QPRNq5GEtxO5BT0JguKncYVyPb5r8F2W1EmtT8qW/cM3EpriKk7e13pMBzcxdOA7x0tPr3ZXhB9N+GxcO2FqUv0QOWbA0Gswt560KTl3n7xv2CWXnt9XNGic5W6k5HUixQyAQGX2XfcpIAa8FHctcMnMCAsvuoHpnHP9oCIkumPiJqcck5k+9AArn7Qo1K1WjMr2YwF5bbmg/WENI8SBzexv5YMk2KEdqKApk+F2x4PpltdGsW1Fo8WiINI+7K+Fj2g+4tF1CMNQudRYSiHjpfRMhNC7bOcdelGRy298zz7Koq8NnNeGxoHSWi2E8x5q/kb16Ov5s9ToOHynkgU/Qgbk8lG4AIzj72PO4AuCwOKWP6g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: audiomuse-ai-config
      namespace: torrent
