---
# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
kube-prometheus-stack:
  crds:
    enabled: true
    upgradeJob:
      enabled: true
      forceConflicts: true

  alertmanager:
    alertmanagerSpec:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi  
      externalUrl: https://alertmanager.k3s.nf.lab
      forceEnableClusterMode: true
      alertmanagerConfigMatcherStrategy: 
        type: None
      persistentVolumeClaimRetentionPolicy:
        whenDeleted: Retain
        whenScaled: Retain
      storage:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations: 
        cert-manager.io/cluster-issuer: nf-lab
        cert-manager.io/private-key-rotation-policy: Always
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        external-dns.alpha.kubernetes.io/target: traefik.k3s.nf.lab
      hosts:
        - alertmanager.k3s.nf.lab
      tls:
        - secretName: alertmanager-general-tls
          hosts:
            - alertmanager.k3s.nf.lab
  grafana:
    enabled: true
    admin:
      existingSecret: grafana-admin-credentials
      userKey: admin-user
      passwordKey: admin-password
    envFromSecrets:
      - name: grafana-influxdb-ups-token
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: influxdb:upsdata
            uid: dfqjx64h8joqoa
            type: influxdb
            access: proxy
            url: http://influxdb-svc.databases.svc.cluster.local:8086
            editable: true
            isDefault: false
            jsonData:
              version: Flux
              organization: nf
              defaultBucket: upsdata/autogen
            secureJsonData:
              token: ${INFLUXDB_UPSDATA_TOKEN}
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: nf-lab
        cert-manager.io/private-key-rotation-policy: Always
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        external-dns.alpha.kubernetes.io/target: traefik.k3s.nf.lab
      hosts:
        - grafana.k3s.nf.lab
      tls:
        - secretName: grafana-general-tls
          hosts:
            - grafana.k3s.nf.lab
    sidecar:
      dashboards:
        enabled: true
        annotations:
          grafana_folder: Kubernetes
        folderAnnotation: grafana_folder
        provider:
          foldersFromFilesStructure: true
      datasources:
        enabled: true

  prometheus:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations: 
        cert-manager.io/cluster-issuer: nf-lab
        cert-manager.io/private-key-rotation-policy: Always
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        external-dns.alpha.kubernetes.io/target: traefik.k3s.nf.lab
      hosts:
        - prometheus.k3s.nf.lab
      tls:
        - secretName: prometheus-general-tls
          hosts:
            - prometheus.k3s.nf.lab

    prometheusSpec:
      command: ["/bin/sh", "-c", "sleep 3600"]
      resources:
        requests:
          cpu: 1000m
          memory: 2Gi
        limits:
          cpu: 2000m
          memory: 4Gi
      externalUrl: https://prometheus.k3s.nf.lab
      ruleSelector: {}
      ruleNamespaceSelector: {}
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      serviceMonitorNamespaceSelector: {}
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelector: {}
      podMonitorNamespaceSelector: {}
      podMonitorSelectorNilUsesHelmValues: false
      additionalScrapeConfigsSecret:
        enabled: false
        name: additional-scrape-configs
        key: prometheus-additional.yaml
      persistentVolumeClaimRetentionPolicy:
        whenDeleted: Retain
        whenScaled: Retain
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi

  defaultRules:
    rules:
      etcd: false
      kubeProxy: false
      kubeSchedulerAlerting: false
      kubeSchedulerRecording: false
      kubeControllerManager: false
      

## Component scraping
#  kubeProxy:
#    enabled: false

#  kubeEtcd:
#    enabled: false
     
#  kubeScheduler:
#    enabled: false
