---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: pgadmin-auth
  namespace: databases
spec:
  encryptedData:
    password: AgA/rCpeGC+uii/oFi3uAtsu7cooDtvtiYFaHiyEUV/zYcgMUaXEJRY0DY5oBFG36BzG5Z920rP8bVJLuPG93qbIbb0Dd4QemLtTqHcxYuJqr+cX53M0jh7tcnAWrIWZpFNY8ouHqJtNBLaB8BXPmf9M9f9USd3U9kIjNS6NdihVug7zwdT2Z8xdg6BeSVRAM/NQdUeNhUdIoAtrISdaMTtcwBAQI2UqwwLDHAqB0PH7lTBbskTAdFid/jn8BkQLFUWHnSr9+6ucHj9MUIv1NA5vbgk8Qs1cDvfZ8TxWWAhQy6BUuhxCuSGNJV1gp7AUtgwiZNh/94RXCV1avwU0Rdme4i0xq25uxlHiHbX8Y2cJ4p3fvxeQ2fFyNKIAkuI64ArAmbLjy/6OggfY6Fy59Vnj5Oaw7/AdXaE/uu0Lyu9IFiTvdWFNMG1H6ahuvgElutMJw71Ha7Eg/xFy7s1s4NMKvQ3h8EMYzPYhZtl5qfV68TmXshGE5DTWBnyUD4vmkfLTntcgYs7Aapo7P1FZ04jMIoiQ0ISl7Eq1QvhUQZPfchwHxwzU+30nLG+CBCNQTT2yxv6E8NJB8XYDZ6D6cDQj6M83h+MW85/VWpME/izp/xffTQ7U9iSoFkxRFaU8HoZCmjlyo0M9M1T+UMvWJe7tEhDtD1/8ex1kSWf4sMa3GL5JY8MlR7dY4m5xtztjxx+4qcnvseP4mVM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: pgadmin-auth
      namespace: databases
