apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - adguard-dns-sync-env-sealed.yaml
  - deployment.yaml
  - rbac.yaml

configMapGenerator:
  - name: adguard-dns-sync-script
    files:
      - assets/main.py
