---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-1246d6c0-1436-46e5-8a6d-af3fedeadf82
  labels:
    openebs.io/storage-engine-type: zfs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: openebs-zfspv-lz4
  csi:
    driver: zfs.csi.openebs.io
    volumeHandle: ssd01-k8s-pvc-1246d6c0-1436-46e5-8a6d-af3fedeadf82
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
  namespace: camera
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: openebs-zfspv-lz4
  volumeName: pvc-1246d6c0-1436-46e5-8a6d-af3fedeadf82
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-2fc408d8-1820-45e5-8abe-04d16310b756
  labels:
    openebs.io/storage-engine-type: zfs
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: openebs-zfspv-lz4
  csi:
    driver: zfs.csi.openebs.io
    volumeHandle: ssd01-k8s-pvc-2fc408d8-1820-45e5-8abe-04d16310b756
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media
  namespace: camera
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: openebs-zfspv-lz4
  volumeName: pvc-2fc408d8-1820-45e5-8abe-04d16310b756
