apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
  namespace: camera
  labels:
    app.kubernetes.io/instance: frigate
    app.kubernetes.io/name: frigate
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    "helm.sh/resource-policy": keep
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: openebs-zfspv-lz4

