apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aurral-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
