apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app: youtubarr

namespace: torrent

resources:
  - youtubarr-config-sealed.yaml
  - youtubarr-oauth-sealed.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - ingress.yaml
