---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: youtubarr-oauth
  namespace: media
spec:
  encryptedData:
    oauth.json: AgA3iN0Trbt0A73qwZIsxNq/2b0rjr82ZmOQPU8+rz2UuI5TCoIB0ZvQa1O7nvHBXLnL5Kb/1eHKF8wzIW7IaaVs0gAIE/kA0TFuwj33NgcBn9H3JmhruoiSI5bnTmagKIIMyGmJu+/KT6sjIf/kykHuj4v2dV8NK5hS2xQiOiIIlJbi5Gph28ltvr7BdW+cr+Qs10iPW5VJ9tmgekrOVnY4kJMCxu+1HxsiaB/wSuIec1JJy8UbeuGYM/tI2Ujoih6KE+YgCs/8MjR7VNoEJ/gvjOOPIiGIeZS8e8AXJri0ETxI/YHWK3hJLdgC4yzFkFSGHF52kOJvkaVFDHTNp2/p1drMhYWSvy0iTtLIXe9xChI1XFXUX0YageJa3aLuuaKRuJu4pY3nPOdlH2EhqJOQkWti9DTb9qxkxCw4bQqY1r9gJpoNicgQ+8B+PG1VP/P1ToikxxIRyEBrDqOemQJTP0w7is+62tC8PSJcUDIlHhzxaJvxOteYtPHCA63QQimigL6qkXqIwKks477OZ6LItj7Nh3egE8R4TAlStKJbfLQeffU4XtYZI0CIqsihzdK86GeTvNMfsW5woDWHeujAgLZ6R9ZRcw3dYhofqyZIZHjj5A/Pi6EGdagmHPNgB7UWqQ5XUKf3z8VPSh0QWS+JHXjZy5BqD9ky8NPvqKFECZX+63EJry78Ole9rFTi8PP+4KAwrbvaH3lBznQ8t6VcNYyrXOzQW3MAnABYSqNadkOL1J/8ztdJ3LoODx/OTOi1wJ0iYoyWzjPJ793s3LO+X+/20wXH2AcXjTKgxYrvd6WKz5DnIYy8YoJMKgxUOoJDqmtEcdAio4W2GK/jg5yg2Ar5A/LS3nLUks4a0H1iZ6AW1MB7MWOEySZO2cdkL7z7i1hgHqrBrlv/XLbZjW5uN61ahS1btbUDyzIcnwthaw2oW8PAPz1CRychGh3GjDVmppRkadOtFhmUxcbQ+N3sBnXfW+X8nTZDVW0FcXwPM3Qdi/z2coDn2KGamQNeEr5tOwE9LzUBEiOZu65mAcj8dLbqlGkcTQKz3rNzI3wfXIpkr9er9GPjjBbrSxL+X+qAMcwT4eAIfaIrLj1Q4OzPYPpJoSM8EsUfEg38IVWiNuthVN2YDoRHDlO3q6WZJfzGQNy2YnThjvBnpv+GTgfbo1/BumKYUJR60ObTEi7V39Z4Vo/Z8Qku/IKYOQclmJhTv3mzfMub04nBDkMmsqxJno+zjww7mMJLQ5yic601WHjlaKAG1OxFVflwzAjB5mLSkM5tgWN4Euwe45DT3Y4UGrmqTZcmEx3V8zYw4+3sMG/gmj9XcUvM+8spD2kMP0NgPp89FyIkPBbumYRbizQH5ZHIn7TFeyLW4TinxoYWZSF3fEdu0fmG4DU39yC2Tsxn7A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: youtubarr-oauth
      namespace: media
