apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: picard-pvc
  namespace: torrent
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
