apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust the size as needed for your application
  storageClassName: openebs-zfspv-lz4
  