apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pyzor-pvc
  namespace: mail
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-zfspv-lz4
  resources:
    requests:
      storage: 5Gi
