apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subarr-pvc
  namespace: media
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
