---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAWDVD9U/YZUnBZ7+MHdI8eXwOL5DGA09yDuzcuy4MClVetRgqOIRtK76NoaXkiPVnZbvph0gq3kfTMcuPggyOn8giJSSyK9cAdHoa8qeB+TsDVb7gl584lEfzOQtR5ZEhpRF3EG/tYkh46jck6gHGaHAFonPQ/kfnbRl9d+XTn75bOC6vndIUeRIhG6mTulIbhvspm8p8dLy+kp4gjx40gdWLc1UbZTaqakhFyGj7/g6Da7fZu4P1fgVV0g0XW96GwKue6aocc2b/dK+KwIMzI+o+gePmrDrHT83ae0b90D/ZDjJ7mB/WTOTkqPIkE7jFC5k4EkzA9brVNtR+zCqd2zJAe/pIkX5BJAO/qnIEApr5rMy4S9T5UImQ/q3ez3FnyWa4PU+LCRqUe35ENrq+c28jobECWU4jGJ8E4lwAHmm6bgmutqd7kXqvCvtN7MxN2MSsDFVoDdyt9Ft+qYkqBw6JeeZvgi+g7R2mlV2o1PGFsZLpR/4RY16dB1QnK3n2ZMPropsffH3wEqiJTodiNEbU6ZH8DGIbb5H9g9PbtJq41UVRTKWyhTAAeVVa7/RjZcqFMX2cRsO6BJjzayBmF+9sOXE7Kt/OetlkBe3X5+zsZyFPvXYBg1t4xOED171Bf/P0ZcGL0gtORc16FDTu0Wd68H4AzIyr62Xbd6dPzIoFoxXd/uqkiseS4i2DVWTZ+fV5Nhg==
    admin-user: AgAhyLDGKqYsomvOwU34mWLUUqU1GDUqxy4Jvejf3BYH7rayKCNbIAhZckm5+TGthXTjs78RaijpFn5ytNIG1OWfyvcJP9imWKCriuralwTj9m9dPDJy37rP1XMui+L5qFiZaCTN2F+wwT9rI9kwjehBNyls5erl52Fv/bG3GJqScMTakLG6BzM+wBtcvi7O7MmHelz6mybIvQ3i/99IXp+A2771jpded4hyK+d1CxmKqOD2kCBFh4jXSjv3LgAMDCxEoJjuBG2mH2+WisSVce9SOgGBCn8FCtCbaw52TZSJCqAzFupbosyVDaRRzqEL+tXvvij6iI1AhSN4babfn7Uk38Vyd3qJvRn4Q90QDil7X+QeDX4SoWRnHi8tt3yeOOds7X3ZGgxV4WEbtyV51hJIKzTap8uODouPitZdoP3X0D0HLUufYQ4OAcueMhXUljojs0pOJgOpUYFLF+gMRTzbiRrtqAc0FK67jSVWgFq69VOFTrthDRMDtcIMLoLGPGLBqFiwdG3/vgRmYUa8BFTosxGGyrAEQ/EzF+l5R/2uLnpJwTNeoqZReryfUYDGa2XxQX2AzMM4aaIvSMYNdAGMNQlsOtwk1EOsHseOdId8Q8V1gA/7msND71ezPaZ9JF64EULTqO4685V9+T6V8y2S6jKJvM/iSkvsQUx2pDUDDwSH72ZqBTz6fD3gjMkfu7uU0MtQog==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: grafana-admin-credentials
      namespace: monitoring
