---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCzybVmbuFVc6KLB8Q2RIh9WiYfs1E6RKXf8+uLdBK3/AgyBQhfQYZyideZlZzNpbDsVxnS1XGIEHHVjWstowtSMxVNMgTNnHaP8RBdmR42NPAmYfIaVtA0AqPmNM3QVbhn7dslwoVdn29RByhBSS+hSfuGtrMBYF6xLroRcIQqlANSiND5AtM3QcVTFlTiBMANdCqPQ3yoJLEPgNb/ap458jM6z8TqhI/cPbfnl5N8ofUGhcId5Fb3EMrCYmV5rIkH5BCef5yUllyRrg1Y9oNKgfCLM/MQlYpf9W4vukgzRn5P5G745enOlRGe//5U3eSLkIJtKKrC4cjlf2hVxRRCgQ6mW/XUU/nGS6nlOHV38SiIeDMX8GJcOy/XsOw6S++OLyX3Dgxn893Sl83eFom8GQ8uA8ELiNUnzBC1w3yLAyHXc1xuk1KXyQiHsIf8Eo/s2gGlzH40ALC1ybR3jxDtfPYCxuUA4/X2EjSnHLjxbRzFXEMqGnSK0N/fevyFfhzxCGX+qvXnpGB+5BCe4bnp1y3kl1n3D5cR8R3ruJ8vgrh2VHfqA5qqFu596cAL6oJkcFEflL13ZmxORKBrI3jrprWuJhW9Xo1/PcYgc1hyTBxkukeJh8BOB2iTE5cob+X4qrPDR8h8LsymEngkB3D2lHqWXWw2CqAXM/N8aWTNzIWkT3sxhtf8COdEtGkIwEmghi9CAQ==
    admin-user: AgBa7GZC1Z6EPk9pqFU6SVnbTGGiYcevgPOrou7i51+mZmJPlgRuHH5QHoyl/srthxdgG6887igGTW+rMM/SoM10q/BpPV4xKTLdeCkRak37tJRQRYA+OfxlcG4RGeZQkakm2TP6L1ht2UH5vMW6YYVOuYKCjCHNGnbdAWzW0UHvWtOADahUqBcIV1TovcT1QFJmtKXPHsYdCk9+DrC5u22pXOIroCE+Dba7K7MSXjgijasAs3bI0f6Bf1hLgCriSATw3B9q70rB5H/lRLCVJ+oYMpFi5GtH6BNCgUo0YrYXSGfI7RU/LPbdN7PlZSvwiz9N+teYZENufnS1hW1woEvieNgoD8ejNKzSr1zwicVhkbvod4DEwIv5YOHx9+HWYdB2Bq+DsbDs3CIlUwzHyecsIUfvGkvaMV/oHMzZA8TJggmoqSh/82z1SfLkXgfa/bnmLUyxMWX1IGzNRMSDMZ7nj8ovyOSvbjo84ZWNqWofjipi3BDL4SEDZazSwWCMdQvy9Qcy/4iL/hDIEhDYPzWvy4joLuYuuxRfz9Kwa2HFOqDwj5DfWZQl8MTZZ9f3vuQtp2TPRHtbY8/E0c6FVjMnmTvbQtToyNkcVH1/NNRc8Iji27Jfhs3yQxg58LycGXru9+TT0OmugYuP+iGTdlrzeO48lcxtiwCEDbVnFwKvmaK5CjQoFZD1QnkAn/W68MH5Um+b4g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
