---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCoaa0R9QIR4RprWTmfdy7mMI3UqOFDbJ1nxQtYrM0pEdVN8tIPpEjTM1YPIYpOfKi3ejEEtaZ3aOlCJrJbDRSHdk/VaDuKOpVX9VNo6IgiHwF5Ba/O5/IqiSyON2LSdaxdJ6VC7gZmyD3w4QC9rX7i1qS8e3+8S+tcF79CYOnJyGtNSaKYKJttqAM5zhpGRZ3BMg9D+Uou/SjCZSj0CoCpz/JqxXcYkmVuniUpCxzJa7R+rmOgKA9/K4Td3DOHSpQ5aI8q4nsGeH8iQalV9VHAK3JajmhOZAZvoDOMr7ZE7GfQ3TEzWlD2wJDu+DEabYI2W9CUVpztPI8fdKSxGJnavHlWm3ghh5I0FtJV9QPBTH9ra6qZ991qzHEZ8ZIsTi3kTqsEISJliESNtfa5hj7UScahLGk/8MfoZrNEBPzQFNnKnNUSoJuAzsDKNevkUQpeYRLvNQUrUW4gz9V575o3/sQ7F+/sLmxCTIMw0NwAf8E3aCUVogoQ4iP58tm6QO0RK03+lXQPJr3GkXD9RxU80g/HXh9i1VttaulqRgyH/b2/T9YnBY7l6xk6ACcXlSAxVSbKGUtHsnwC5EdwHE99ZE9gwS7jaLpg3Upqg/lFIfPxyVGbtRWHtnJtoROtn+pa7w8wRWAsMW7y2E+eCU+DQFh+T36gTOKoNygCyT/6x3Pd/khAmn2hevFTXUT0K41CgjWrmaQrC5s=
    admin-user: AgCahj9XWNHZHExH0MdFEjXD0OIPcBK0IHW+TGHZvNCIGGGWaxCdxrWh8mgcIm97JMnd+ERGRMkkiEzavXVVEljpHkE8R0/LCzXDed5aHjLfelejKbxjHrgX85d1r0VCCaO7O1xNNwyAKYfez28g/Tuy42RiCJHjxp9HZ/hm2cfi/8fON4dFP3ShUkIqLnY+++IyXsIkvlZlwbk6i92A38f8iIN9Fi++61pAV72JT3xuA6dNuR6+4hl+Ljzp53A4LZEVO3GVrddEsV5sXtUo1o1850Y48T/FIaIXemkYptt18/1wwf4coUu0ah12Ks/IYADkAtpZoHlzeUAFazP9IFnzztcR5n2FGMQIutzHFIPnijgV1TDUKhsgfZcoRrfK2kgOXj+lbMninSLa9LNVcLCYH3rTmUV/uRxcDkcN5isTGk7y7/EIAbEDLMUrP6V+iQ5neGHhZxxZ97zVa79NmXwWuuM1MChWfq59BYUvFpY4A3miy+qHFvJWcbIVD0tRJPODdUkTI4rjpT14IW091nM1wmqslC5YnXNpdAiFee50tSsYI19Tgf6WSE4AlTpjAKSwrHU70wsL17NDYjE/g8t0KBJ8KWNJSg3uceAqR3oS5RayzU2MjpWrw82rJeOKHjp21f3Qmkz8U19luEx0219kaYfbJLzvO4ImXrsiqmf0OyxAYmboorVlDcjcYdY1QAofKILWxQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
