# https://github.com/seerr-team/seerr/blob/develop/charts/seerr-chart/values.yaml

seerr:
  probes:
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 5

    readinessProbe:
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 5
    startupProbe:
      tcpSocket:
        port: http

  config:
    persistence:
      existingClaim: 'jellyseerr-pvc'

  ingress:
    enabled: false

