apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret-sync-sa.yaml
  - secret-sync-role-torrent.yaml
  - secret-sync-rolebinding-torrent.yaml
  - secret-sync-role-databases.yaml
  - secret-sync-rolebinding-databases.yaml
  - secret-sync-cronjob.yaml
  - configmap.yaml
  - flask-deployment.yaml
  - flask-service.yaml
  - worker-deployment.yaml
