apiVersion: batch/v1
kind: CronJob
metadata:
  name: pg-db-app-secret-sync
  namespace: torrent
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: pg-db-app-secret-sync
          restartPolicy: OnFailure
          containers:
            - name: secret-sync
              image: bitnami/kubectl:1.31.4
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -ec
                - |
                  kubectl get secret pg-db-app -n databases -o go-template='{{printf "apiVersion: v1\nkind: Secret\nmetadata:\n  name: %s\n  namespace: torrent\ntype: %s\ndata:\n" .metadata.name .type}}{{range $k,$v := .data}}{{printf "  %s: %s\n" $k $v}}{{end}}' \
                    | kubectl apply -f -
