apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pg-db-app-secret-sync-reader
  namespace: databases
subjects:
  - kind: ServiceAccount
    name: pg-db-app-secret-sync
    namespace: torrent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pg-db-app-secret-sync-reader
