apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pg-db-app-secret-sync-reader
  namespace: databases
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["pg-db-app"]
    verbs: ["get"]
