apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: torrent-radarr-daily-local
  namespace: velero
spec:
  schedule: CRON_TZ=America/New_York 50 6 * * *
  skipImmediately: false
  template:
    includedNamespaces:
      - torrent
    includedResources:
      - '*'
    labelSelector:
      matchLabels:
        app: radarr
    ttl: 168h0m0s
    snapshotVolumes: true
    snapshotMoveData: false
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: torrent-radarr-weekly-offsite-cfr2
  namespace: velero
spec:
  schedule: CRON_TZ=America/New_York 50 6 * * 3
  skipImmediately: false
  template:
    includedNamespaces:
      - torrent
    includedResources:
      - '*'
    labelSelector:
      matchLabels:
        app: radarr
    ttl: 720h0m0s
    snapshotVolumes: true
    snapshotMoveData: true
