apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subgen-models-pvc
  namespace: ai
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    helm.sh/resource-policy: keep  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
